CREATE DATABASE QLTS

USE QLTS
GO

CREATE TABLE KHUVUC(
MAKV INT,
TENKV NVARCHAR(50),
UUTIEN FLOAT,
PRIMARY KEY (MAKV)
)

CREATE TABLE QUEQUAN(
MAQQ INT,
TENQQ NVARCHAR(50),
PRIMARY KEY (MAQQ)
)


CREATE TABLE THISINH(
MATS INT,
HO NVARCHAR(40),
TEN NVARCHAR(10),
PHAI BIT,
NAMSINH DATETIME,
MAKV INT,
MAQQ INT,
PRIMARY KEY (MATS),
FOREIGN KEY (MAKV) REFERENCES KHUVUC(MAKV),
FOREIGN KEY (MAQQ) REFERENCES QUEQUAN(MAQQ)
)

CREATE TABLE KQTS(
MATS INT,
DMON1 FLOAT,
DMON2 FLOAT,
DMON3 FLOAT,
GHICHU NVARCHAR(100),
PRIMARY KEY (MATS),
FOREIGN KEY (MATS) REFERENCES THISINH(MATS)
)

--XET KHOA CHÍNH SAU KHI TAO BANG
ALTER TABLE HSSV ADD PRIMARY KEY (MaSV)

Hoặc:

ALTER TABLE HSSV ADD CONSTRAINT Ma PRIMARY KEY (MaSV, MaLop)

-- XÓA KHÓA CHÍNH
ALTER TABLE HSSV DROP PRIMARY KEY;

Hoặc:

ALTER TABLE HSSV DROP CONSTRAINT Ma

--XET KHOA NGOAI SAU KHI TAO BANG
ALTER TABLE THISINH
ADD CONSTRAINT FK_THISINH_MAQQ
  FOREIGN KEY (MAQQ) 
  REFERENCES QUEQUAN(MAQQ);

--XÓA KHÓA NGOAI
ALTER TABLE DiemSV DROP FOREIGN KEY Ma

----lấy dữ liệu từ access
INSERT INTO KHUVUC(MAKV, TENKV, UUTIEN) SELECT DISTINCT MAKV, TENKV, UUTIEN FROM TuyenSinhFull

----CAU 3
SELECT TOP 1 KHUVUC.MAKV, KHUVUC.TENKV, COUNT (MATS) TS
FROM KHUVUC, THISINH 
WHERE KHUVUC.MAKV = THISINH.MAKV
GROUP BY KHUVUC.MAKV, KHUVUC.TENKV
ORDER BY TS DESC
GO

----CAU 4: TẠO VIEW
CREATE VIEW V_HIENTHI
AS
SELECT THISINH.MATS, THISINH.HO, THISINH.TEN,(KQTS.DMON1 + KQTS.DMON2 + KQTS.DMON3) AS 'TONGDIEM'
 FROM THISINH, KHUVUC, KQTS, QUEQUAN WHERE THISINH.MAKV = KHUVUC.MAKV AND KHUVUC.TENKV = N'Khu vực 1' 
AND KQTS.MATS = THISINH.MATS AND QUEQUAN.MAQQ = THISINH.MAQQ AND QUEQUAN.TENQQ = N'Vĩnh Long' 
AND (KQTS.DMON1 + KQTS.DMON2 + KQTS.DMON3) >=15

---GOI VIEW
SELECT * FROM V_HIENTHI


---VIET THU TUC (PROCEDURE) THÊM 1 KHUVUC
CREATE PROCEDURE THEMKHUVUC (@MA INT, @TEN NVARCHAR(50), @UUTIEN FLOAT)
AS
BEGIN
	INSERT INTO KHUVUC VALUES (@MA, @TEN, @UUTIEN)
END
EXEC THEMKHUVUC 6, 'KIENG GIANG', 8

SELECT *FROM KHUVUC

---VIET THU TUC (PROCEDURE) THÊM 1 QUEQUAN
CREATE PROCEDURE QUEQUAN (@MA INT, @TEN NVARCHAR(50), @UUTIEN FLOAT)
AS
BEGIN
	INSERT INTO QUEQUAN VALUES (@MA, @TEN, @UUTIEN)
END

EXEC QUEQUAN 6, 'KIENG GIANG', 8

SELECT *FROM QUEQUAN

SELECT COUNT(*) FROM QUEQUAN

SELECT MIN(DMON1) FROM KQTS

--Sắp xếp kết quả trong SQL
SELECT danh_sach_cot 
FROM ten_bang 
[WHERE dieu_kien] 
[ORDER BY cot1, cot2, .. cotN] [ASC | DESC];

--Để lấy các hàng với thứ tự ưu tiên riêng, truy vấn SELECT sẽ như sau:
SQL> SELECT * FROM SINHVIEN
    ORDER BY (CASE KHOAHOC
    WHEN 'TCNH' 	 THEN 1
    WHEN 'KTDN' 	 THEN 2
    WHEN 'CNTT' 	 THEN 3
    ELSE 100 END) ASC, KHOAHOC DESC;